# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-13 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.IntegerField(choices=[(0, '编辑推荐'), (1, '名家撰稿')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_src',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
