# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-13 02:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20180313_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '联系我们'), (1, '游戏反馈'), (2, '网站反馈')], default=0)),
                ('body', models.TextField(max_length=200)),
                ('ctime', models.DateTimeField()),
                ('name', models.TextField(max_length=10)),
                ('contact', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
                ('excerpt', models.CharField(max_length=12)),
                ('type', models.IntegerField(choices=[(0, '礼品'), (1, '服饰'), (2, '文具'), (3, '其他')], default=0)),
                ('like_num', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('size', models.CharField(max_length=20)),
                ('img_src', models.ImageField(upload_to='upload')),
                ('product_src1', models.ImageField(upload_to='upload')),
                ('product_src2', models.ImageField(upload_to='upload')),
                ('product_src3', models.ImageField(upload_to='upload')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
