# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-13 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180313_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='ctime',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.TextField(default='匿名', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.TextField(default='匿名', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
