# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-15 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180315_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.CharField(default='匿名', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='匿名', max_length=10),
        ),
    ]
